# Generated by Django 2.2.6 on 2020-04-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200429_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
