# Generated by Django 3.0.6 on 2020-05-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_address'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histroy',
            name='content_type',
        ),
        migrations.AddField(
            model_name='histroy',
            name='click',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='histroy',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.restro'),
        ),
    ]
