# Generated by Django 2.2.6 on 2020-05-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200429_1513'),
        ('home', '0002_restro_closetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restro',
            old_name='name',
            new_name='restroname',
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('restroname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.restro')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('foodname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata')),
            ],
        ),
    ]
