# Generated by Django 2.2.6 on 2020-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200501_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='/static/images/restaurant.jpg', upload_to='fpics'),
        ),
        migrations.AddField(
            model_name='restro',
            name='image',
            field=models.ImageField(default='/static/images/restaurant.jpg', upload_to='pics'),
        ),
    ]
