# Generated by Django 2.2.6 on 2020-05-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200502_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restroname',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.restro'),
        ),
    ]
