# Generated by Django 3.0.6 on 2020-05-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200429_1513'),
        ('home', '0005_cart_restroname'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('house', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata')),
            ],
        ),
    ]
