# Generated by Django 3.0.6 on 2020-06-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_restro_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restroname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restro', to='home.restro'),
        ),
    ]
