# Generated by Django 3.0.6 on 2020-06-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200602_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='catagery',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='contain',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
