# Generated by Django 3.0.6 on 2020-05-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restroname', models.CharField(max_length=300)),
                ('foodname', models.CharField(max_length=500)),
                ('date', models.DateField(null=True)),
                ('total', models.BigIntegerField()),
                ('address', models.CharField(max_length=800)),
                ('foodsid', models.CharField(max_length=200)),
                ('restroid', models.BigIntegerField()),
                ('quantity', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
