# Generated by Django 3.0.6 on 2020-06-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_orders_foodimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='foodimage',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='foodname',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restroname',
        ),
    ]
