# Generated by Django 3.0.6 on 2020-06-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200607_1052'),
        ('myaccount', '0003_auto_20200608_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='restroid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.restro'),
        ),
    ]
